#generating database
DROP DATABASE IF EXISTS STUMPED;
CREATE DATABASE STUMPED;
USE STUMPED;

#generating tables
CREATE TABLE MAIL(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(100),
	UNIQUE(EMAIL)
);

CREATE TABLE USERTYPE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TYPE VARCHAR(15)
);

CREATE TABLE USER (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERTYPEID INT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(255),
	ISVERIFIED INT NOT NULL DEFAULT 0,
	UNIQUE (Email),
	FOREIGN KEY (USERTYPEID) REFERENCES USERTYPE(ID)
);

CREATE TABLE EVENT (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255),
	TIME VARCHAR(255),
	LOCATION VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	LINK VARCHAR(255)
);

CREATE TABLE CONTACTTYPE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TYPE VARCHAR(15)
);

CREATE TABLE CONTACT (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CONTACTTYPEID INT NOT NULL,
	TITLE VARCHAR(255),
	FIRSTNAME VARCHAR(255),
	LASTNAME VARCHAR(255),
	USERTYPE VARCHAR(255),
	GENDER VARCHAR(255),
	AGEGROUP VARCHAR(255),
	EMAIL VARCHAR(100),
	PHONENUMBER VARCHAR(100),
	SUBJECT VARCHAR(255),
	MESSAGE VARCHAR(255),
	FOREIGN KEY (CONTACTTYPEID) REFERENCES CONTACTTYPE(ID)
);

#some initial population
INSERT INTO USERTYPE (TYPE) VALUES ('ADMIN'), ('PROFESSIONAL'), ('PATIENT');
INSERT INTO CONTACTTYPE (TYPE) VALUES ('CONTACT'), ('STORY'), ('EVENT');


	